// <auto-generated />
namespace N01432018_RoomReservation_PassionProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class room_bookings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(room_bookings));
        
        string IMigrationMetadata.Id
        {
            get { return "202106110009246_room_bookings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
